.github/release-drafter.yaml
.github/release.yaml
.github/workflows/pullRequest-lint.yaml
.github/workflows/release-drafter.yaml
.github/workflows/release.yaml

Add workflows:
- Pull Request Linter
- Release Drafter
- GH Release
These workflows will ensure to build automatically nice GH Release Notes.
Linting will ensure to have PR titles following conventional commits on which drafter rely on.
Drafter will run on 2 actions: When a PR is opened and when a PR is merged. When 
- opened/reopened/syncronized, drafter will autolabel the PR according to the PR title
- merged, drafter will create a release draft. According to the PR title, drafter will select apprpriate semVer based version number. If previous release was for example `v0.1.2`  and the PR title is `feature: Lorem Ipsum dolor` the release draft will bump minor version number to `v0.2.0`.
GH Release will be published when pushing a matching GH Tag to the repositories `main` branch and use …

ci: add workflows managing releases

---

.github/workflows/quality-check-pr.yaml
README.md
action.yaml

This PR adds an `action.yaml`, so that the quality check command can be run as GitHub action, like mentioned in #3

feat: create composite GitHub action to run quality checks

---

.github/release-drafter.yaml
.github/workflows/release.yaml

For now, disable `skipChangelog` autolabeler. After merging PR, changes in GH workflows will be listed in release notes again.

chore(ci): disable `skipChangelog` autolabeler

---

CHANGELOG.md
internal/changelog_exists.go
internal/globals.go
internal/install_exists.go
internal/install_exists_test.go
internal/readme_exists.go
internal/test_runner.go
internal/test_runner_mock.go
internal/test_runner_test.go
internal/types.go

Implemented new method `IsOptional` in interface `QualityGuideline` to cover optional checks (aka `INSTALL.md` or `AUTHOR.md`(→ TRG 2.03)).
Added new feature to test if optional file 'INSTALL.md' exists. If the file does not exist, this test fails (for now) but not the test run itself (does not exit 1):
```shell
$ go run main.go checkLocal
Running local checks of eclipse-tractusx release guidelines
Testing Quality Guideline: TRG 1.01 - README.md
Testing Quality Guideline: TRG 1.02 - INSTALL.md
Failed! Test failed, but marked as optional. More infos: Did not find optional INSTALL.md file in current directory.
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
Testing Quality Guideline: TRG 1.03 - CHANGELOG.md
```
Closes #10

feat: check INSTALL.md (TRG 1.02)

---

internal/globals.go
internal/repo_structure_exists.go
internal/repo_structure_exists_test.go
internal/test_runner.go

---
title: 'feat: implementation of repo structure check'
---
PR introduces a new tractusx-quality-check feature validating repository structure as per [TRG 2.03 guideline](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) .
Please ensure to do as many of the following checks as possible, before asking for committer review:
- [V] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [V] Copyright and license header are present on all affected files
- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if …

feat: add repo structure check

---

internal/default_branch.go
internal/repo_structure_exists.go
internal/repo_structure_exists_test.go
internal/test_runner.go
pkg/product/metadata.go
pkg/product/metadata_test.go
pkg/repo/repoinfo.go

1. The fix adds verification of the source repository whether it is a leading repository. Based on that includes or not 'docs' and 'charts' dirs to mandatory check. 
2. Implementation also incorporates new package 'repo' for basic repository metadata, making the code which was previously contained in the default branch check reusable to other components.
3. Finally it refines subject check code from having another condition in the test runner for a case where test should pass with optional information. 
updates https://github.com/eclipse-tractusx/sig-infra/issues/93
updates https://github.com/eclipse-tractusx/sig-infra/issues/151
updates https://github.com/eclipse-tractusx/tractusx-quality-checks/issues/20
Fixes #20
Please ensure to do as many of the following checks as possible, before …

fix: repo structure check requires docs and charts dirs only for leading repos now + new package 'repo'

---

.tractusx

This PR updates the `.tractusx` repository metadata file. 
The updated metadata does declare [eclipse-tractusx/sig-infra](https://github.com/eclipse-tractusx/sig-infra) as leading repository and also points to other repositories related to `sig-infra`.
The leading repository is changed, so the quality checks workflow does not treat this repository like a product repository.
Currently the workflow is failing, since we do not provide a `/docs` and `/charts` folder. 
While `/docs` at least has a chance to be created in near future, `/charts` will most likely never be present.
We could also think of other ways to make the check a bit more "clever". Maybe introducing repo types (product, leading, docs, helper, etc.) or introduce an `--ignore` flag to our checks command.

chore: update repository metadata

---

.tractusx
action.yaml

This PR adjusts the quality-check action to run the quality checks on a pre-built binary, that is downloaded from a GitHub release in this repository.
The version to install is configurable via action input and currently defaults to our last release.
Closes #21

feat(action): run checks via pre-built binary

---

.github/workflows/release-drafter.yaml

If an invalid PR title has been selected while creating the PR, the PR lint workflow will complain about it and the release drafter has not labeled the PR.
After editing the PR title to macht the linter the release drafter isn't triggered again to label the PR. Added _edited_ type to trigger release drafter after editing the PR title.

chore: update workflow trigger for pull request

---

internal/repo/default_branch.go
pkg/repo/repoinfo.go

This PR changes the behavior of the default branch check.
__Old behavior:__ Automatically fail, when running on a fork
__New behavior:__ Automatically pass, when running on a fork
__Reason:__ We do not need (and want) to enforce any repo settings on repositories, that contributions are made from.
This could interfere with development processes, without any benefit to the contribution itself.
Instead, it leads to failing quality checks, without an available workaround. 
Automatically passing the default branch check on forks does not change the quality of contributions and also does not interfere with outside repo settings
Fixes #34

fix: auto-pass default branch check on forks

---

internal/container/allowed_base_image_check.go
internal/container/allowed_base_image_check_test.go

Using the correct image name for Eclipse Temurin and fixing tests that worked on wrong assumptions
related to #36

fix: correct temurin docker image name for base image check

---

internal/filesystem/filesystem.go
pkg/repo/repo_structure_exists.go
pkg/repo/repo_structure_exists_test.go

The PR fixes reported issue with regards to multiple DEPENDENCIES files presence in repository structure. With the fix quality check accepts now the case where there is more files with DEPENDENCIES prefix, i.e. DEPENDENCIES_FRONTEND, DEPENDENCIES_BACKEND. 
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/230
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93
Please ensure to do as many of the following checks as possible, before asking for committer review:

fix: multiple dependencies files accepted by repo structure check

---

.github/workflows/release.yaml
action.yaml

The goal of the PR is to support binaries build for multiple os/architectures. The change was implemented in the existing release workflow. It introduces binaries builds for following platforms:
- linux/386
- linux/amd64
- windows/386
- windows/amd64
- darwin/amd64
- Darwin/arm64
Fixes https://github.com/eclipse-tractusx/tractusx-quality-checks/issues/27
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93

feat: enabling multiple platforms binaries

---

.tractusx
pkg/tractusx/metadata.go
pkg/tractusx/metadata_test.go
pkg/tractusx/test/metadata_test_template.yaml

PR to enhance metadata structure including repository category. The option is to be used in the dashboard in order to present categorised repositories in separate sections. PR includes also .tractusx update with populated flag.
Updates https://github.com/eclipse-tractusx/sig-infra/issues/261
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93

chore: metadata enhancement with repo category

---

README.md

PR to describe how to setup tractusx quality check pre-commit hook. It allows developer to validate TRGs compliance locally. Speeds up the process and helps determine potential issues before it's pushed to remote repository. 
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/90
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93

docs: how to setup tractusx quality check pre-commit hook description

---

pkg/container/allowed_base_image_check.go

- add 'alpine' as allowed base-image
updates https://github.com/eclipse-tractusx/sig-infra/issues/259
Please ensure to do as many of the following checks as possible, before asking for committer review:

chore: add alpine as allowed base image

---

.github/workflows/dash-licence-check.yaml

This PR runs a dash-license check on each PR, to verify if the `DEPENDENCIES` file is up-to-date before merging to main

chore(build): run dash license check on each PR

---

pkg/container/allowed_base_image_check.go
pkg/helm/helmchart_structure_exists.go
pkg/tractusx/types.go

PR to add quality checks web optimised. New struct field was added to store web error messages, to be used by quality dashboard for better user experience. Currently are two ways to present err message CLI (default) and WEB. Allowed base image and helm structure checks have been adopted to new method. 
Updates https://github.com/eclipse-tractusx/sig-infra/issues/265

feat: web format errors

---

docs/README.md
docs/metadata_file.md
internal/filesystem/filesystem_test.go
pkg/container/allowed_base_image_check.go
pkg/container/allowed_base_image_check_test.go
pkg/container/dockerfile.go
pkg/container/dockerfile_test.go
pkg/helm/helmchart_structure_exists.go
pkg/helm/helmchart_structure_exists_test.go
pkg/helm/resource_mgmt_check_test.go
pkg/repo/repo_structure_exists_test.go
pkg/repo/repoinfo.go
pkg/tractusx/metadata.go
pkg/tractusx/metadata_test.go
pkg/tractusx/test/metadata_test_template.yaml
pkg/tractusx/types.go

This PR introduces a new section to our `.tractusx` metadata file. The section `skipReleaseChecks.alignedBaseImage` allows to configure file paths to `Dockerfiles`, that are not published to DockerHub. The configuration is based on trust and is not verified automatically. 
If Dockerfiles are configured to skip the aligned base image check, the automated TRG checks will not report issues on that Dockerfile, even if it is not based on images aligned via TRG 4.02.
This PR also adds a first chapter to the `/docs` folder. I think that can be useful in multiple ways
- We can link to documentation related to the metadata file and reference to it in the TRG, so we do not duplicate content
- We have an easier entry for everyone, who want to contribute
- We can document decisions and reasons behind …

feat: skip aligned base image check based on metadata config

---

cmd/checkLocal.go

A new environment variable called `CHECKLOCAL_BASEDIR` that can be used with the checkLocal cmd and changes the path for the TRG checks. It still defaults to "./" when not set.
Please ensure to do as many of the following checks as possible, before asking for committer review:

feat: env variable to set basedir for checkLocal

---

pkg/helm/helmchart_structure_exists.go
pkg/helm/resource_mgmt_check.go
pkg/helm/resource_mgmt_check_test.go

This PR can be seen as a proposal and is totally up for discussion.
What I want to emphasize with my changes is, that we should keep clear method signatures. Some of the functions I changed returned some kind of error state often represented by a boolean and an error description as string. This can be handled by using the builtin `error` object. In my opinion having an `error` as return type in the method signature does make it clearer, that there is an unwanted state. Looking at `(bool, string)` on the other hand does not make it as clear in my opinion and one has to check the variable names used to return the values.
I also amended the `getMissingChartFiles` in `pkg/helm/helmchart_structure_exists.go` by changing the parameters. 
In this case, the function took a parameter, that was …

refactor: make error cases clear in method signatures
